modbus:
  - name: Wafe
    type: tcp
    host: 10.0.0.76
    port: 502
    close_comm_on_error : false
    delay : 2
    retries: 10
    retry_on_empty: true
    switches:
      - name: "Wafe sleep"
        address: 0
        slave: 1
        write_type: coil
        verify:
          delay: 5
      - name: "Wafe short boost"
        address: 1
        slave: 1
        write_type: coil
        verify:
          delay: 1
      - name: "Wafe long boost"
        address: 2
        slave: 1
        write_type: coil
        verify:
          delay: 1
      - name: "Wafe hollyday"
        address: 3
        slave: 1
        write_type: coil
        verify:
          delay: 1
      - name: "Wafe circulation"
        address: 4
        slave: 1
        write_type: coil
        verify:
          delay: 1
      - name: "Wafe fireplace"
        address: 5
        slave: 1
        write_type: coil
        verify:
          delay: 1
      - name: "Wafe silent"
        address: 6
        slave: 1
        write_type: coil
        verify:
          delay: 1
      - name: "Wafe intelligent mode"
        address: 7
        slave: 1
        write_type: coil
        verify:
          delay: 0
      - name: "Wafe scheduller mode"
        address: 8
        slave: 1
        write_type: coil
        verify:
          delay: 0
      - name: "Wafe manual mode"
        address: 9
        slave: 1
        write_type: coil
        verify:
          delay: 0
    sensors:
      - name: "Outside Air"
        unit_of_measurement: °C
        slave: 1
        address: 0
        count: 1
        input_type: input
        data_type: int
        scale: 0.1
        offset: 0
        precision: 1
      - name: "Fresh Air"
        unit_of_measurement: °C
        slave: 1
        address: 1
        count: 1
        input_type: input
        data_type: int
        scale: 0.1
        offset: 0
        precision: 1
      - name: "Indoor Air"
        unit_of_measurement: °C
        slave: 1
        address: 2
        count: 1
        input_type: input
        data_type: int
        scale: 0.1
        offset: 0
        precision: 1
      - name: "Waste Air"
        unit_of_measurement: °C
        slave: 1
        address: 3
        count: 1
        input_type: input
        data_type: int
        scale: 0.1
        offset: 0
        precision: 1
      - name: "Humidity Outside In"
        unit_of_measurement: "%"
        slave: 1
        address: 4
        count: 1
        input_type: input
        data_type: int
        scale: 0.1
        offset: 0
        precision: 1
      - name: "Humidity Inside In"
        unit_of_measurement: "%"
        slave: 1
        address: 5
        count: 1
        input_type: input
        data_type: int
        scale: 0.1
        offset: 0
        precision: 1
      - name: "Humidity Inside Out"
        unit_of_measurement: "%"
        slave: 1
        address: 6
        count: 1
        input_type: input
        data_type: int
        scale: 0.1
        offset: 0
        precision: 1
      - name: "Humidity Outside Out"
        unit_of_measurement: "%"
        slave: 1
        address: 7
        count: 1
        input_type: input
        data_type: int
        scale: 0.1
        offset: 0
        precision: 1
      - name: "CO2 Inside"
        unit_of_measurement: ppm
        slave: 1
        address: 8
        count: 1
        input_type: input
        data_type: int
        scale: 1
        offset: 0
        precision: 0 
      - name: "Fresh Air Fan Perc"
        unit_of_measurement: "%"
        slave: 1
        address: 9
        count: 1
        input_type: input
        data_type: int
        scale: 1
        offset: 0
        precision: 0  
      - name: "Fresh Air Fan Flow"
        unit_of_measurement: "m³/h"
        slave: 1
        address: 10
        count: 1
        input_type: input
        data_type: int
        scale: 1
        offset: 0
        precision: 0
      - name: "Fresh Air Fan RPM"
        unit_of_measurement: "RPM"
        slave: 1
        address: 11
        count: 1
        input_type: input
        data_type: int
        scale: 1
        offset: 0
        precision: 0 
      - name: "Exhaust Air Fan Perc"
        unit_of_measurement: "%"
        slave: 1
        address: 12
        count: 1
        input_type: input
        data_type: int
        scale: 1
        offset: 0
        precision: 0  
      - name: "Exhaust Air Fan Flow"
        unit_of_measurement: "m³/h"
        slave: 1
        address: 13
        count: 1
        input_type: input
        data_type: int
        scale: 1
        offset: 0
        precision: 0
      - name: "Exhaust Air Fan RPM"
        unit_of_measurement: "RPM"
        slave: 1
        address: 14
        count: 1
        input_type: input
        data_type: int
        scale: 1
        offset: 0
        precision: 0 
      - name: "Fresh Filter Status"
        unit_of_measurement: "%"
        slave: 1
        address: 30
        count: 1
        input_type: input
        data_type: int
        scale: 1
        offset: 0
        precision: 0
      - name: "Exhaust Filter Status"
        unit_of_measurement: "%"
        slave: 1
        address: 31
        count: 1
        input_type: input
        data_type: int
        scale: 1
        offset: 0
        precision: 0